spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_demo
    username: root
    password: 190627
  data:
    redis:
      host: localhost
      port: 6739

